Fix Sync Gateway issues

diff --git a/modules/run-couchbase-server/run-couchbase-server b/modules/run-couchbase-server/run-couchbase-server
--- a/modules/run-couchbase-server/run-couchbase-server
+++ b/modules/run-couchbase-server/run-couchbase-server
@@ -69,6 +69,7 @@ function print_usage {
   echo -e "  --data-ramsize\t\tThe data service memory quota in MB. Only used if --manage-memory-manually is set."
   echo -e "  --index-ramsize\t\tThe index service memory quota in MB. Only used if --manage-memory-manually is set."
   echo -e "  --fts-ramsize\t\t\tThe full-text service memory quota in MB. Only used if --manage-memory-manually is set."
+  echo -e "  --create-bucket-for-testing\t\tCreate a bucket in the Couchbase cluster. Should ONLY be used for testing!"
   echo -e "  --help\t\t\tShow this help text and exit."
   echo
   echo "Example:"
@@ -614,6 +615,37 @@ function start_couchbase {
   sudo systemctl start couchbase-server
 }
 
+function create_bucket_for_testing {
+  local readonly bucket_name="$1"
+  local readonly node_hostname="$2"
+  local readonly node_port="$3"
+  local readonly username="$4"
+  local readonly password="$5"
+
+  log_info "Creating bucket $bucket_name for testing"
+
+  local create_bucket_args=()
+  create_bucket_args+=("bucket-create")
+  create_bucket_args+=("--cluster=$node_hostname:$node_port")
+  create_bucket_args+=("--username=$username")
+  create_bucket_args+=("--password=$password")
+  create_bucket_args+=("--bucket=$bucket_name")
+  create_bucket_args+=("--bucket-type=couchbase")
+  create_bucket_args+=("--bucket-ramsize=100")
+
+  set +e
+  local out
+  out=$("$COUCHBASE_CLI" "${create_bucket_args[@]}")
+  set -e
+
+  if string_contains "$out" "SUCCESS: Bucket created"; then
+    log_info "Successfully created bucket $bucket_name."
+  else
+    log_error "Failed to create bucket $bucket_name. Log output:\n$out."
+    exit 1
+  fi
+}
+
 # The main entrypoint for this code
 function run {
   local services="$DEFAULT_SERVICES"
@@ -636,6 +668,8 @@ function run {
   local fts_port="$DEFAULT_SEARCH_PORT"
   local memcached_port="$DEFAULT_MEMCACHED_PORT"
   local xdcr_port="$DEFAULT_XDCR_PORT"
+
+  local bucket_for_testing
 
   while [[ $# > 0 ]]; do
     local key="$1"
@@ -730,6 +764,11 @@ function run {
         xdcr_port="$2"
         shift
         ;;
+      --create-bucket-for-testing)
+        assert_not_empty "$key" "$2"
+        bucket_for_testing="$2"
+        shift
+        ;;
       --help)
         print_usage
         exit
@@ -808,6 +847,10 @@ function run {
       "$fts_ramsize" \
       "$index_ramsize" \
       "$services"
+
+    if [[ ! -z "$bucket_for_testing" ]]; then
+      create_bucket_for_testing "$bucket_for_testing" "$node_hostname" "$rest_port" "$cluster_username" "$cluster_password"
+    fi
   else
     log_info "The rally point for cluster $cluster_name is $rally_point_hostname."
     join_existing_cluster \
