Do server-add in a retry loop
Erlang port mapper seems to be flaky

diff --git a/modules/run-couchbase-server/run-couchbase-server b/modules/run-couchbase-server/run-couchbase-server
--- a/modules/run-couchbase-server/run-couchbase-server
+++ b/modules/run-couchbase-server/run-couchbase-server
@@ -381,13 +381,6 @@ function add_server_to_cluster {
 
   wait_for_cluster_to_be_initialized "$rally_point_hostname" "$rest_port" "$cluster_name" "$cluster_username" "$cluster_password"
 
-  if node_is_added_to_cluster "$rally_point_hostname" "$rest_port" "$cluster_username" "$cluster_password" "$node_hostname"; then
-    log_info "Node $node_hostname has already been added to cluster $cluster_name. Will not add again."
-    return
-  fi
-
-  log_info "Adding node $node_hostname:$rest_port to cluster $cluster_name with rally point $rally_point_hostname"
-
   local server_add_args=()
 
   server_add_args+=("server-add")
@@ -399,18 +392,37 @@ function add_server_to_cluster {
   server_add_args+=("--server-add-password=$cluster_password")
   server_add_args+=("--services=$services")
 
-  # The couchbase-cli may exit with an error, so make sure that doesn't cause this whole script to exit with an error
-  set +e
-  local out
-  out=$("$COUCHBASE_CLI" "${server_add_args[@]}")
-  set -e
+  local readonly server_add_max_retries=5
+  local readonly sleep_between_server_add_retries_sec=15
 
-  if string_contains "$out" "SUCCESS: Server added"; then
-    log_info "Successfully added node $node_hostname:$rest_port to cluster $cluster_name."
-  else
-    log_error "Failed to add node $node_hostname:$rest_port to cluster $cluster_name. Log output:\n$out."
-    exit 1
-  fi
+  for (( i=0; i<"$server_add_max_retries"; i++ )); do
+    if node_is_added_to_cluster "$rally_point_hostname" "$rest_port" "$cluster_username" "$cluster_password" "$node_hostname"; then
+      log_info "Node $node_hostname has already been added to cluster $cluster_name. Will not add again."
+      return
+    fi
+
+    log_info "Adding node $node_hostname:$rest_port to cluster $cluster_name with rally point $rally_point_hostname"
+
+    # The couchbase-cli may exit with an error, so make sure that doesn't cause this whole script to exit with an error
+    set +e
+    local out
+    out=$("$COUCHBASE_CLI" "${server_add_args[@]}")
+    set -e
+
+    if string_contains "$out" "SUCCESS: Server added"; then
+      log_info "Successfully added node $node_hostname:$rest_port to cluster $cluster_name."
+      return
+    elif string_contains "$out" "ERROR: Prepare join failed. Failed to reach erlang port mapper."; then
+      log_warn "Got an error about failing to reach the erlang port mapper. Sometimes this means the Security Group settings are incorrect, but occasionally, this is an intermittent error that goes away on its own. Will sleep for $sleep_between_server_add_retries_sec seconds and try again."
+      sleep "$sleep_between_server_add_retries_sec"
+    else
+      log_error "Failed to add node $node_hostname:$rest_port to cluster $cluster_name. Log output:\n$out."
+      exit 1
+    fi
+  done
+
+  log_error "Failed to add node $node_hostname:$rest_port to cluster $cluster_name after $server_add_max_retries retries."
+  exit 1
 }
 
 # Rebalance the cluster. This command must be called each time you add a new node; until it's called, the node will not
