Fix couchbase-cli error handling and retries

diff --git a/modules/run-couchbase-server/run-couchbase-server b/modules/run-couchbase-server/run-couchbase-server
--- a/modules/run-couchbase-server/run-couchbase-server
+++ b/modules/run-couchbase-server/run-couchbase-server
@@ -14,6 +14,7 @@ source "$BASH_COMMONS_INSTALL_DIR/strings.sh"
 
 readonly COUCHBASE_BASE_DIR="/opt/couchbase"
 readonly COUCHBASE_BIN_DIR="$COUCHBASE_BASE_DIR/bin"
+readonly COUCHBASE_CLI="$COUCHBASE_BIN_DIR/couchbase-cli"
 
 readonly DEFAULT_SERVICES="data,index,query,fts"
 readonly DEFAULT_INDEX_STORAGE_SETTING="default"
@@ -121,13 +122,6 @@ function get_rally_point_hostname {
   echo -n "$hostname"
 }
 
-# Run the couchbase CLI with the given arguments.
-function couchbase_cli {
-  local readonly args=($@)
-
-  "$COUCHBASE_BIN_DIR/couchbase-cli" "${args[@]}"
-}
-
 # Returns true (0) if the Couchbase cluster has already been initialized and false otherwise.
 function cluster_is_initialized {
   local readonly rally_point_hostname="$1"
@@ -184,7 +178,7 @@ function get_cluster_status {
   # cause this entire script to exit as a result
   set +e
   local out
-  out=$(couchbase_cli "${server_list_args[@]}")
+  out=$("$COUCHBASE_CLI" "${server_list_args[@]}")
   set -e
 
   echo -n "$out"
@@ -356,8 +350,11 @@ function init_new_cluster {
     cluster_init_args+=("--cluster-fts-ramsize=$fts_ramsize")
   fi
 
+  # The couchbase-cli may exit with an error, so make sure that doesn't cause this whole script to exit with an error
+  set +e
   local out
-  out=$(couchbase_cli "${cluster_init_args[@]}")
+  out=$("$COUCHBASE_CLI" "${cluster_init_args[@]}")
+  set -e
 
   if string_contains "$out" "SUCCESS: Cluster initialized"; then
     log_info "Successfully initialized cluster $cluster_name"
@@ -381,6 +378,13 @@ function add_server_to_cluster {
   local readonly node_port="$8"
   local readonly services="$9"
 
+  wait_for_cluster_to_be_initialized "$rally_point_hostname" "$rally_point_port" "$cluster_name" "$cluster_username" "$cluster_password"
+
+  if node_is_added_to_cluster "$rally_point_hostname" "$rally_point_port" "$cluster_username" "$cluster_password" "$node_hostname" "$node_port"; then
+    log_info "Node $node_hostname has already been added to cluster $cluster_name. Will not add again."
+    return
+  fi
+
   log_info "Adding node $node_hostname:$node_port to cluster $cluster_name with rally point $rally_point_hostname"
 
   local server_add_args=()
@@ -395,8 +399,11 @@ function add_server_to_cluster {
   server_add_args+=("--index-storage-setting=$index_storage_setting")
   server_add_args+=("--services=$services")
 
+  # The couchbase-cli may exit with an error, so make sure that doesn't cause this whole script to exit with an error
+  set +e
   local out
-  out=$(couchbase_cli "${server_add_args[@]}")
+  out=$("$COUCHBASE_CLI" "${server_add_args[@]}")
+  set -e
 
   if string_contains "$out" "SUCCESS: Server added"; then
     log_info "Successfully added node $node_hostname:$node_port to cluster $cluster_name."
@@ -414,6 +421,10 @@ function rebalance_cluster {
   local readonly cluster_name="$3"
   local readonly cluster_username="$4"
   local readonly cluster_password="$5"
+  local readonly node_hostname="$6"
+  local readonly node_port="$7"
+
+  wait_for_cluster_to_be_initialized "$rally_point_hostname" "$rally_point_port" "$cluster_name" "$cluster_username" "$cluster_password"
 
   local rebalance_args=()
 
@@ -424,18 +435,28 @@ function rebalance_cluster {
   rebalance_args+=("--no-progress-bar")
 
   local readonly rebalance_max_retries=5
+  local readonly sleep_between_rebalance_retries_sec=15
 
   for (( i=0; i<"$rebalance_max_retries"; i++ )); do
+    if node_is_active_in_cluster "$rally_point_hostname" "$rally_point_port" "$cluster_username" "$cluster_password" "$node_hostname" "$node_port"; then
+      log_info "Node $node_hostname is already active in cluster $cluster_name. Will not rebalance."
+      return
+    fi
+
     log_info "Rebalancing cluster $cluster_name with rally point $rally_point_hostname"
 
+    # The couchbase-cli may exit with an error, so make sure that doesn't cause this whole script to exit with an error
+    set +e
     local out
-    out=$(couchbase_cli "${rebalance_args[@]}")
+    out=$("$COUCHBASE_CLI" "${rebalance_args[@]}")
+    set -e
 
     if string_contains "$out" "SUCCESS: Rebalance complete"; then
       log_info "Successfully rebalanced cluster $cluster_name."
       return
     elif string_contains "$out" "ERROR: Rebalance failed. See logs for detailed reason. You can try again."; then
-      log_warn "Rebalance failed. This may be because another node requested a rebalance at the same time. Will sleep for $SLEEP_BETWEEN_RETRIES_SEC seconds and try again."
+      log_warn "Rebalance failed. This may be because another node requested a rebalance at the same time. Will sleep for $sleep_between_rebalance_retries_sec seconds and try again."
+      sleep "$sleep_between_rebalance_retries_sec"
     else
       log_error "Got unexpected error when trying to rebalance cluster $cluster_name. Log output:\n$out."
       exit 1
@@ -459,35 +480,27 @@ function join_existing_cluster {
   local readonly node_hostname="$8"
   local readonly services="$9"
 
-  wait_for_cluster_to_be_initialized "$rally_point_hostname" "$rally_point_port" "$cluster_name" "$cluster_username" "$cluster_password"
-
   log_info "Joining cluster $cluster_name"
 
-  if node_is_added_to_cluster "$rally_point_hostname" "$rally_point_port" "$cluster_username" "$cluster_password" "$node_hostname" "$node_port"; then
-    log_info "Node $node_hostname has already been added to cluster $cluster_name. Will not add again."
-  else
-    add_server_to_cluster \
-      "$rally_point_hostname" \
-      "$rally_point_port" \
-      "$cluster_name" \
-      "$cluster_username" \
-      "$cluster_password" \
-      "$index_storage_setting" \
-      "$node_hostname" \
-      "$node_port" \
-      "$services"
-  fi
+  add_server_to_cluster \
+    "$rally_point_hostname" \
+    "$rally_point_port" \
+    "$cluster_name" \
+    "$cluster_username" \
+    "$cluster_password" \
+    "$index_storage_setting" \
+    "$node_hostname" \
+    "$node_port" \
+    "$services"
 
-  if node_is_active_in_cluster "$rally_point_hostname" "$rally_point_port" "$cluster_username" "$cluster_password" "$node_hostname" "$node_port"; then
-    log_info "Node $node_hostname is already active in cluster $cluster_name. Will not rebalance."
-  else
-    rebalance_cluster \
-      "$rally_point_hostname" \
-      "$rally_point_port" \
-      "$cluster_name" \
-      "$cluster_username" \
-      "$cluster_password"
-  fi
+  rebalance_cluster \
+    "$rally_point_hostname" \
+    "$rally_point_port" \
+    "$cluster_name" \
+    "$cluster_username" \
+    "$cluster_password" \
+    "$node_hostname" \
+    "$node_port"
 }
 
 # Check that the user has not manually specified any of the memory settings and exit with an error if they have. To
